CREATE TABLE tb_filme(
id BIGINT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(255) UNIQUE NOT NULL,
faixa_etaria ENUM('LIVRE', 'MAIS_10', 'MAIS_12', 'MAIS_14', 'MAIS_16', 'MAIS_18') NOT NULL,
genero ENUM('ACAO', 'AVENTURA', 'ANIMACAO', 'COMEDIA', 'DRAMA', 'FICCAO CIENTIFICA', 'ROMANCE', 'SUSPENSE', 'TERROR', 'OUTROS') NOT NULL,
descricao TEXT
);